language: go
go:
  - tip
sudo: required
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database guble;' -U postgres
before_install:
  - go get github.com/wadey/gocovmerge github.com/mattn/goveralls golang.org/x/tools/cmd/cover
script:
  - GO_TEST_DISABLED=true go test -v -short $(go list ./... | grep -v /vendor/) && GO_TEST_DISABLED=true go test -v -tags cluster $(go list ./... | grep -v /vendor/)
after_success:
  - scripts/generate_coverage.sh
  - goveralls -coverprofile=full_cov.out -service=travis-ci
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      GOOS=linux go build -a --ldflags '-linkmode external -extldflags "-static"' . ;
      GOOS=linux go build -a --ldflags '-linkmode external -extldflags "-static"' -o ./guble-cli/guble-cli ./guble-cli ;
    fi
    docker build -t cosminrentea/gobbler . ;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
    docker push cosminrentea/gobbler ;
