
[[dependencies]]
  branch = "master"
  name = "github.com/Bogh/gcm"

[[dependencies]]
  branch = "master"
  name = "github.com/Shopify/sarama"

[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/azer/snakecase"

[[dependencies]]
  branch = "master"
  name = "github.com/cosminrentea/go-uuid"

[[dependencies]]
  branch = "master"
  name = "github.com/docker/distribution"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/mock"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/mux"

[[dependencies]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[dependencies]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[dependencies]]
  branch = "master"
  name = "github.com/hashicorp/memberlist"

[[dependencies]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[[dependencies]]
  branch = "master"
  name = "github.com/jpillora/backoff"

[[dependencies]]
  branch = "master"
  name = "github.com/mattn/go-sqlite3"

[[dependencies]]
  branch = "master"
  name = "github.com/pkg/profile"

[[dependencies]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[dependencies]]
  branch = "master"
  name = "github.com/rs/xid"

[[dependencies]]
  branch = "master"
  name = "github.com/sideshow/apns2"

[[dependencies]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[dependencies]]
  branch = "master"
  name = "github.com/ugorji/go"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  name = "gopkg.in/alecthomas/kingpin.v2"
